-- Ripple Supabase Schema

-- 1. Create profiles table linked to auth.users
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

drop policy if exists "Public profiles are viewable by everyone" on public.profiles;
create policy "Public profiles are viewable by everyone" on public.profiles for select using (true);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- Trigger to automatically create profile on user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Ripple User'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', '')
  );
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Create events table
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  title text not null,
  description text,
  category text default 'Roads',
  location text not null,
  latitude numeric(9,6) default 13.3521,
  longitude numeric(9,6) default 74.7947,
  distance numeric(4,1) default 0.4,
  seen integer default 1,
  confirmed integer default 0,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for events
alter table public.events enable row level security;

drop policy if exists "Allow public read access to events" on public.events;
create policy "Allow public read access to events" on public.events for select using (true);

drop policy if exists "Allow public insert to events" on public.events;
create policy "Allow public insert to events" on public.events for insert with check (true);

drop policy if exists "Allow updates to event counts" on public.events;
create policy "Allow updates to event counts" on public.events for update using (true);

drop policy if exists "Allow owner to delete event" on public.events;
create policy "Allow owner to delete event" on public.events for delete using (auth.uid() = user_id or user_id is null);

-- 3. Seed initial mock data
insert into public.events (title, description, category, location, distance, seen, confirmed, image)
values
  ('Water logging near MIT Road', 'Heavy rain causing accumulation of water near the road.', 'Roads', 'Near MIT Main Gate, Manipal', 0.4, 42, 56, 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=1200&q=85'),
  ('Water logging near MIT Main Gate', 'Water standing at main entrance disrupting pedestrian flow.', 'Water', 'MIT Main Gate, Manipal', 1.2, 34, 34, 'https://images.unsplash.com/photo-1547683905-f686c993aae5?auto=format&fit=crop&w=1200&q=85'),
  ('Streetlight not working near Tiger Circle', 'Dark area at night making turns unsafe.', 'Electricity', 'Tiger Circle, Manipal', 2.1, 18, 18, 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=85'),
  ('Tree fallen near KMC', 'Large branch blocking side path.', 'Environment', 'Near KMC, Manipal', 3.4, 27, 22, 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1200&q=85');
